#!/usr/bin/python3
"""
    RSA Factoring Challenge
    Optional Project
"""
import sys
import math


def main():
    """ Main program """
    if len(sys.argv) != 2:
        print("wrong length dude")
        return
    with open(sys.argv[1], 'r') as f:
        f = f.readlines()
        for line in f:
            n = m = int(line)
            if n % 2 == 0:
                i = int(n / 2)
                n = 2
                print("{}={}*{}".format(m, i, n))
            else:
                for i in range(3, int(math.sqrt(m)) + 1):
                    if n % i == 0:
                        n = int(n / i)
                        print("{}={}*{}".format(m, n, i))
                        break

if __name__ == "__main__":
    main()
